#!/usr/bin/env bash
# Installing nginx on webserver
# listening port 80:

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
